services:
  rssy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-8080}
      - SITE_NAME=${SITE_NAME:-rssy}
      - SITE_URL=${SITE_URL:-http://localhost:8080}
    restart: unless-stopped
