package parser

import (
	"fmt"
	"net/url"
	"time"

	"github.com/mmcdole/gofeed"
)

func (p *Parser) validate(feed *gofeed.Feed) *ValidationResult {
	result := &ValidationResult{
		Checks: []ValidationCheck{},
	}

	// Channel/Feed level checks
	result.addCheck(p.checkTitle(feed))
	result.addCheck(p.checkLink(feed))
	result.addCheck(p.checkDescription(feed))
	result.addCheck(p.checkLanguage(feed))
	result.addCheck(p.checkLastBuildDate(feed))
	result.addCheck(p.checkGenerator(feed))
	result.addCheck(p.checkImage(feed))

	// Item level checks
	result.addCheck(p.checkItemCount(feed))
	result.addCheck(p.checkItemTitles(feed))
	result.addCheck(p.checkItemLinks(feed))
	result.addCheck(p.checkItemDates(feed))
	result.addCheck(p.checkItemGUIDs(feed))
	result.addCheck(p.checkItemDescriptions(feed))

	// Calculate score
	result.calculateScore()

	return result
}

func (v *ValidationResult) addCheck(check ValidationCheck) {
	v.Checks = append(v.Checks, check)
}

func (v *ValidationResult) calculateScore() {
	v.MaxScore = 0
	v.Score = 0

	for _, check := range v.Checks {
		switch check.Severity {
		case "error":
			v.MaxScore += 10
			if check.Passed {
				v.Score += 10
			}
		case "warning":
			v.MaxScore += 5
			if check.Passed {
				v.Score += 5
			}
		case "info":
			v.MaxScore += 2
			if check.Passed {
				v.Score += 2
			}
		}
	}

	v.IsValid = true
	for _, check := range v.Checks {
		if !check.Passed && check.Severity == "error" {
			v.IsValid = false
			break
		}
	}
}

func (p *Parser) checkTitle(feed *gofeed.Feed) ValidationCheck {
	if feed.Title == "" {
		return ValidationCheck{
			Name:     "Feed Title",
			Passed:   false,
			Message:  "Feed is missing a title element",
			Severity: "error",
		}
	}
	return ValidationCheck{
		Name:     "Feed Title",
		Passed:   true,
		Message:  "Feed has a valid title",
		Severity: "error",
	}
}

func (p *Parser) checkLink(feed *gofeed.Feed) ValidationCheck {
	if feed.Link == "" {
		return ValidationCheck{
			Name:     "Feed Link",
			Passed:   false,
			Message:  "Feed is missing a link to the website",
			Severity: "error",
		}
	}
	if _, err := url.ParseRequestURI(feed.Link); err != nil {
		return ValidationCheck{
			Name:     "Feed Link",
			Passed:   false,
			Message:  "Feed link is not a valid URL",
			Severity: "error",
		}
	}
	return ValidationCheck{
		Name:     "Feed Link",
		Passed:   true,
		Message:  "Feed has a valid website link",
		Severity: "error",
	}
}

func (p *Parser) checkDescription(feed *gofeed.Feed) ValidationCheck {
	if feed.Description == "" {
		return ValidationCheck{
			Name:     "Feed Description",
			Passed:   false,
			Message:  "Feed is missing a description",
			Severity: "warning",
		}
	}
	return ValidationCheck{
		Name:     "Feed Description",
		Passed:   true,
		Message:  "Feed has a description",
		Severity: "warning",
	}
}

func (p *Parser) checkLanguage(feed *gofeed.Feed) ValidationCheck {
	if feed.Language == "" {
		return ValidationCheck{
			Name:     "Language",
			Passed:   false,
			Message:  "Feed does not specify a language",
			Severity: "info",
		}
	}
	return ValidationCheck{
		Name:     "Language",
		Passed:   true,
		Message:  "Feed specifies language: " + feed.Language,
		Severity: "info",
	}
}

func (p *Parser) checkLastBuildDate(feed *gofeed.Feed) ValidationCheck {
	if feed.UpdatedParsed == nil && feed.PublishedParsed == nil {
		return ValidationCheck{
			Name:     "Last Update Date",
			Passed:   false,
			Message:  "Feed does not have a last build/update date",
			Severity: "warning",
		}
	}
	return ValidationCheck{
		Name:     "Last Update Date",
		Passed:   true,
		Message:  "Feed has a valid update date",
		Severity: "warning",
	}
}

func (p *Parser) checkGenerator(feed *gofeed.Feed) ValidationCheck {
	if feed.Generator == "" {
		return ValidationCheck{
			Name:     "Generator",
			Passed:   false,
			Message:  "Feed does not specify a generator",
			Severity: "info",
		}
	}
	return ValidationCheck{
		Name:     "Generator",
		Passed:   true,
		Message:  "Generated by: " + feed.Generator,
		Severity: "info",
	}
}

func (p *Parser) checkImage(feed *gofeed.Feed) ValidationCheck {
	if feed.Image == nil || feed.Image.URL == "" {
		return ValidationCheck{
			Name:     "Feed Image",
			Passed:   false,
			Message:  "Feed does not have an image/logo",
			Severity: "info",
		}
	}
	return ValidationCheck{
		Name:     "Feed Image",
		Passed:   true,
		Message:  "Feed has an image",
		Severity: "info",
	}
}

func (p *Parser) checkItemCount(feed *gofeed.Feed) ValidationCheck {
	count := len(feed.Items)
	if count == 0 {
		return ValidationCheck{
			Name:     "Item Count",
			Passed:   false,
			Message:  "Feed contains no items",
			Severity: "warning",
		}
	}
	return ValidationCheck{
		Name:     "Item Count",
		Passed:   true,
		Message:  formatItemCount(count),
		Severity: "warning",
	}
}

func formatItemCount(count int) string {
	if count == 1 {
		return "Feed contains 1 item"
	}
	return fmt.Sprintf("Feed contains %d items", count)
}

func (p *Parser) checkItemTitles(feed *gofeed.Feed) ValidationCheck {
	missing := 0
	for _, item := range feed.Items {
		if item.Title == "" {
			missing++
		}
	}
	if missing > 0 {
		return ValidationCheck{
			Name:     "Item Titles",
			Passed:   false,
			Message:  fmt.Sprintf("%d item(s) missing title", missing),
			Severity: "error",
		}
	}
	return ValidationCheck{
		Name:     "Item Titles",
		Passed:   true,
		Message:  "All items have titles",
		Severity: "error",
	}
}

func (p *Parser) checkItemLinks(feed *gofeed.Feed) ValidationCheck {
	missing := 0
	invalid := 0
	for _, item := range feed.Items {
		if item.Link == "" {
			missing++
		} else if _, err := url.ParseRequestURI(item.Link); err != nil {
			invalid++
		}
	}
	if missing > 0 || invalid > 0 {
		msg := ""
		if missing > 0 {
			msg = fmt.Sprintf("%d item(s) missing link", missing)
		}
		if invalid > 0 {
			if msg != "" {
				msg += ", "
			}
			msg += fmt.Sprintf("%d item(s) have invalid links", invalid)
		}
		return ValidationCheck{
			Name:     "Item Links",
			Passed:   false,
			Message:  msg,
			Severity: "warning",
		}
	}
	return ValidationCheck{
		Name:     "Item Links",
		Passed:   true,
		Message:  "All items have valid links",
		Severity: "warning",
	}
}

func (p *Parser) checkItemDates(feed *gofeed.Feed) ValidationCheck {
	missing := 0
	future := 0
	now := time.Now()

	for _, item := range feed.Items {
		if item.PublishedParsed == nil && item.UpdatedParsed == nil {
			missing++
		} else {
			pubDate := item.PublishedParsed
			if pubDate == nil {
				pubDate = item.UpdatedParsed
			}
			if pubDate != nil && pubDate.After(now.Add(24*time.Hour)) {
				future++
			}
		}
	}

	if missing > 0 || future > 0 {
		msg := ""
		if missing > 0 {
			msg = fmt.Sprintf("%d item(s) missing date", missing)
		}
		if future > 0 {
			if msg != "" {
				msg += ", "
			}
			msg += fmt.Sprintf("%d item(s) have future dates", future)
		}
		return ValidationCheck{
			Name:     "Item Dates",
			Passed:   false,
			Message:  msg,
			Severity: "warning",
		}
	}
	return ValidationCheck{
		Name:     "Item Dates",
		Passed:   true,
		Message:  "All items have valid dates",
		Severity: "warning",
	}
}

func (p *Parser) checkItemGUIDs(feed *gofeed.Feed) ValidationCheck {
	missing := 0
	duplicates := make(map[string]int)

	for _, item := range feed.Items {
		if item.GUID == "" {
			missing++
		} else {
			duplicates[item.GUID]++
		}
	}

	dupCount := 0
	for _, count := range duplicates {
		if count > 1 {
			dupCount++
		}
	}

	if missing > 0 || dupCount > 0 {
		msg := ""
		if missing > 0 {
			msg = fmt.Sprintf("%d item(s) missing GUID", missing)
		}
		if dupCount > 0 {
			if msg != "" {
				msg += ", "
			}
			msg += fmt.Sprintf("%d duplicate GUID(s) found", dupCount)
		}
		return ValidationCheck{
			Name:     "Item GUIDs",
			Passed:   false,
			Message:  msg,
			Severity: "warning",
		}
	}
	return ValidationCheck{
		Name:     "Item GUIDs",
		Passed:   true,
		Message:  "All items have unique GUIDs",
		Severity: "warning",
	}
}

func (p *Parser) checkItemDescriptions(feed *gofeed.Feed) ValidationCheck {
	missing := 0
	for _, item := range feed.Items {
		if item.Description == "" && item.Content == "" {
			missing++
		}
	}
	if missing > 0 {
		return ValidationCheck{
			Name:     "Item Content",
			Passed:   false,
			Message:  fmt.Sprintf("%d item(s) missing description/content", missing),
			Severity: "info",
		}
	}
	return ValidationCheck{
		Name:     "Item Content",
		Passed:   true,
		Message:  "All items have content",
		Severity: "info",
	}
}
